name: Sync to hugging face hub

on : 
  push:
    branches: [main]

  # to run this workflow normally from the Actions tab 
  workflow_dispatch:

jobs:
  sync-to-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Add remote
      env: 
        HF: ${{ secrets.HG }}
      run: git remote add space https://maruseppe:$HF@huggingface.co/spaces/maruseppe/demo_app
      
    - name: Push to Hub
      env: 
        HF: ${{ secrets.HG }}
      run: git push --force https://maruseppe:$HF@huggingface.co/spaces/maruseppe/demo_app main
